// 20 questions per service category. Answers reviewed for tone, not medical advice.
export const FAQ = {
  inject: [
    ["Am I a candidate for injectables?", "If you are over 18, not pregnant or breastfeeding, and have no active skin infection or autoimmune flare, you are usually a candidate. The consultation confirms it in ten minutes."],
    ["Who performs the injection?", "Only physicians and specialist nurses trained in facial anatomy. Nobody injects in this clinic without a medical licence on file."],
    ["Which brands of filler do you use?", "Cross-linked hyaluronic acid from CE-marked European manufacturers. You see the sealed box and batch label before it is opened."],
    ["How long does lip filler last?", "Typically 8–12 months. Metabolism, smoking and heavy exercise shorten it; conservative dosing lengthens it."],
    ["Will my lips look overfilled?", "Not with our protocol. We cap the first session at a small volume, review at two weeks, and add only if the shape asks for it."],
    ["How soon does Botox work?", "First movement changes at day 3, full effect at day 14. We review you at two weeks and refine at no charge."],
    ["How long does Botox last?", "Three to four months for a first treatment, often longer once the muscle is trained by repeat sessions."],
    ["What is Mesobotox and how is it different?", "Micro-droplets placed superficially across a wider area. It softens fine crepe lines and pore texture without freezing expression."],
    ["Is eye mesotherapy safe around the lower lid?", "Yes, with cannula-free micro-needling depth control and a lymphatic-drainage aftercare protocol to limit puffiness."],
    ["What does cheek filler actually change?", "It restores the light-catching edge of the midface, which lifts the nasolabial fold and the jawline indirectly."],
    ["Does jawline filler make a face look wider?", "Only if placed laterally without a plan. We define the angle and the border separately so the face reads sharper, not broader."],
    ["What is an 8-point lift?", "Eight anatomically fixed points across the midface and jaw treated in one sitting to re-suspend descending tissue. No surgery, no downtime."],
    ["Is full-face Botox a lot of product?", "It is a wider map at a lower dose per point — the total is often close to a standard upper-face session."],
    ["Does fat-dissolving injection really work?", "For small, pinchable pockets like the submental area, yes, over 2–4 sessions. It is not a treatment for general weight loss."],
    ["What is a skin booster?", "Non-cross-linked hyaluronic acid placed in the dermis for hydration and glow. It changes quality, not shape."],
    ["What is Profhilo and when do you recommend it?", "A high-concentration bio-remodelling gel for laxity of the cheeks, neck and arms. Two sessions, four weeks apart."],
    ["How is Fillart different from ordinary filler?", "It is a technique, not a product: layered micro-boluses following the light map of the face rather than filling a single line."],
    ["Does it hurt?", "Topical anaesthetic for 20 minutes, lidocaine inside most fillers, ice and vibration during. Most guests rate it 2–3 out of 10."],
    ["What is the downtime?", "Small bruising or swelling for 24–72 hours. Plan any event at least a week after your appointment."],
    ["Can filler be reversed?", "Hyaluronic acid can be dissolved with hyaluronidase within a day if you dislike the result. Neuromodulators simply wear off."]
  ],
  hair: [
    ["Am I too young for a hair transplant?", "Under 25 we usually stabilise loss medically first, then transplant — otherwise the donor is spent chasing a moving hairline."],
    ["FUE or FUT — which do you do?", "Follicular unit extraction, punch by punch. It leaves no linear scar and lets you keep short hair."],
    ["How many grafts will I need?", "A receding hairline is typically 1,800–2,500; a full crown restoration 3,000–4,500. Trichoscopy at consultation gives your number."],
    ["Will the new hairline look natural?", "We draw it against your facial proportion and forehead movement, then place single hairs at the front row and doubles behind."],
    ["Is the result permanent?", "Transplanted follicles come from the donor zone, which is genetically resistant to hormonal thinning, so they behave like donor hair for life."],
    ["When will I see hair?", "Shedding at weeks 2–6, first growth at month 3–4, meaningful density at month 8, final result at month 12–15."],
    ["Does the procedure hurt?", "It is done under local anaesthetic. You are awake, watching a film or sleeping. Soreness the first two nights, managed with simple analgesia."],
    ["How long is the day?", "Six to nine hours including breaks and lunch, depending on graft count."],
    ["When can I go back to work?", "Desk work at day 3–4 with a loose cap. Client-facing work is comfortable from day 10 once redness fades."],
    ["When can I train again?", "Walking from day 3, light gym at day 10, heavy lifting and swimming from week 4."],
    ["What happens to my donor area?", "It is harvested in a diffuse pattern so density drops evenly and invisibly. It is fully covered again in two weeks."],
    ["Can you fix a previous bad transplant?", "Often yes — by redistributing the front row, excising plug grafts and adding density behind. It needs a longer plan."],
    ["Do you transplant eyebrows?", "Yes. Single-hair grafts angled almost flat to the skin, following the natural sweep of each eyebrow section."],
    ["How is beard transplant different?", "Sparser placement, steeper angles and a much finer punch, to read as stubble rather than a hair patch."],
    ["Do women get hair transplants here?", "Yes — for frontal recession, widened parting and post-surgical scars, usually without shaving the recipient area."],
    ["What is Hair Meso?", "A vitamin, peptide and growth-factor cocktail delivered to the scalp to strengthen existing follicles. It complements, not replaces, transplant."],
    ["What is PRP Meso Hair?", "Your own platelet-rich plasma, spun in clinic and injected into the scalp. Typically three sessions a month apart, then maintenance."],
    ["Will I still need medication after surgery?", "Usually yes, to protect the native hair around the graft. The transplant does not stop your original pattern of loss."],
    ["Are there any scars?", "Hundreds of pin-point healing marks under 1 mm, invisible at conversational distance within a month."],
    ["What if a graft does not take?", "We audit density at month 12. Any shortfall against the agreed plan is corrected in a touch-up session at no cost."]
  ],
  surgery: [
    ["Who is a good candidate for blepharoplasty?", "Anyone with hooded upper lids, tired lower lids or fat pads that no longer respond to non-surgical work, in good general health."],
    ["Upper or lower eyelid — how do I know?", "Upper if the crease disappears or the lid touches the lash; lower if the shadow and bag persist rested. Many need both."],
    ["Will it change my expression?", "No. Removing skin restores the eye you had; we do not alter the shape of the aperture unless you ask for it."],
    ["Is it done under general anaesthetic?", "Upper lids under local with light sedation. Lower lids and combined cases under sedation or general, decided with the anaesthetist."],
    ["How long is the operation?", "45–60 minutes for upper lids, 90–120 minutes for a combined four-lid procedure."],
    ["Where are the scars?", "In the natural upper crease and just beneath the lash line, or inside the lid for a transconjunctival approach. Invisible when healed."],
    ["How long is the swelling?", "Peak at day 2–3, socially presentable at day 10–14 with makeup, fully settled at three months."],
    ["When do stitches come out?", "Day 5–7 in clinic, in a five-minute appointment."],
    ["When can I wear contact lenses again?", "Usually two weeks, once the lid margin is comfortable and dryness has resolved."],
    ["What is a Direct Lift?", "A precise excision above the brow or along the jaw that lifts tissue directly, chosen when a thread or filler cannot hold the weight."],
    ["Who is Direct Lift for?", "Mature skin with real laxity, where a mid-face filler plan would add volume without addressing descent."],
    ["Will the scar be visible?", "It is hidden in the brow line or a natural crease, closed in layers and taped for six weeks. It matures pale and flat."],
    ["Can it be combined with injectables?", "Yes — surgery for position, injectables for volume and texture, staged four to six weeks apart."],
    ["How long do surgical results last?", "Eyelid surgery typically 10–15 years. A direct lift holds well but does not stop ageing elsewhere in the face."],
    ["What are the risks?", "Bruising, asymmetry, dry eye and delayed healing are the common ones. Serious complications are rare and are listed in the consent you read at consultation."],
    ["What tests do I need beforehand?", "Bloods, a medication review and an ophthalmic check for lid surgery. Anaesthetic clearance if you are sedated."],
    ["Do I need to stop smoking?", "Yes — four weeks before and four weeks after. Nicotine is the single largest predictor of poor healing."],
    ["Can I fly in for surgery?", "Yes. Plan seven to ten nights locally; we schedule follow-ups on day 2, day 6 and before departure."],
    ["Is anyone allowed to stay with me?", "One companion in recovery and for every follow-up. Overnight stay is arranged when the plan requires it."],
    ["What does aftercare include?", "Dressings, medication, four scheduled reviews, a scar protocol and direct access to your surgeon's line for six weeks."]
  ]
};
